# -*- coding: utf-8 -*-
"""S1_R3 - AT2_LOPAL

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17KOUrx5O1DX6Z5Px1mM3IWHJ6eCXdO6D

***Exercício 1***
"""

for i in range(0, 101):
  if i % 2 == 0:
    print(f"{i} é par")
  else:
    print(f"{i} é impar")

"""***Exercício 2***"""

num1 = input("Digite o primeiro número: ")
num2 = input("Digite o segundo número: ")
num3 = input("Digite o terceiro número: ")
lista = [num1, num2, num3]
lista.sort()
print(lista)

"""***Exercício 3***"""

nome = input("Digite seu nome:")
for i in range(len(nome) + 1):
  print(nome[0:i])

"""***Exercício 4***"""

numero = int(input("Até que numero vc deseja gerar a série de Fibonacci?"))
fib = [1,1]
for i in range(2, numero):
  fib.append(fib[i-2] + fib[i-1])
print(fib[:numero])

"""***Exercício 5***"""

nome = input("Digite seu nome: ")
while len(nome) <= 3:
    print("O nome deve ter mais de 3 caracteres.")
    nome = input("Tente novamente: ")

idade = int(input("Digite sua idade: "))
while idade < 0 or idade > 150:
    print("A idade deve estar entre 0 e 150.")
    idade = int(input("Tente novamente: "))

salario = float(input("Digite seu salário: "))
while salario <= 0:
    print("O salário deve ser maior que zero.")
    salario = float(input("Tente novamente: "))

sexo = input("Digite seu sexo ('f' ou 'm'): ")
while sexo not in ['f', 'm']:
    print("O sexo deve ser 'f' ou 'm'.")
    sexo = input("Tente novamente: ")

estado_civil = input("Estado Civil ('s', 'c', 'v', 'd'): ")
while estado_civil not in ['s', 'c', 'v', 'd']:
    print("Estado civil está inválido.")
    estado_civil = input("Tente novamente")

print("\n--- Dados validados com sucesso! ---")

"""***Exercício 6***"""

numero = int(input("Digite um munero inteiro: "))
if numero > 1:
  primo = True
  for i in range(2, numero):
    if numero % i == 0:
      primo = False
      break
  if primo:
    print(f"{numero} é primo")
  else:
    print(f"{numero} não é primo")

"""***Exercício 7***"""

num = int(input("Fatorial de: "))
resultado = 1
for i in range(1, num + 1):
    resultado *= i
print(f"{num}! = {resultado}")

"""***Exercício 8***"""

L = [5, 7, 2, 9, 4, 1, 3]

print(f"a) Tamanho da lista: {len(L)}")
print(f"b) Maior numero: {max(L)}")
print(f"c) Menor numero: {min(L)}")
print(f"d) Soma: {sum(L)}")
L.sort()
print(f"e) Crescente: {L}")
L.reverse()
print(f"f) Decrescente: {L}")

"""***Exercício 9***"""

from pprint import pprint
Prod_Prec = {"Salgado":4.50, "Lanche":6.50, "Suco":3.00, "Refrigerante":3.50, "Doce":1.00}
pprint(Prod_Prec)

"""***Exercício 10***"""

senha_correta = "676767"
senha_digitada = ""
while senha_digitada != senha_correta:
    senha_digitada = input("Digite sua senha: ")

    if senha_digitada != senha_correta:
        print("Senha incorreta! Tente outra fez.")

print("Acesso liberado")

"""***Exercício 11***"""

num = int(input("Digite um número de 1 a 10: "))

if 1 <= num <= 10:
    print(f"Tabuada do {num}:")
    for i in range(1, 11):
        print(f"{num} x {i} = {num * i}")
else:
    print("Pronto!")